# Generated by Django 3.1.3 on 2020-12-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracacao',
            old_name='data_entra',
            new_name='data_entrada',
        ),
    ]
