# Generated by Django 3.1.3 on 2020-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201202_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Default', max_length=254),
            preserve_default=False,
        ),
    ]
