# Generated by Django 3.1.3 on 2020-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201203_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracacao',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
