# Generated by Django 3.1.3 on 2020-12-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201203_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='berco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.berco'),
            preserve_default=False,
        ),
    ]
